version: "3"
services:
  pi_scan:
    build: .
    # network_mode: bridge
    tty: true
    volumes:
      - ./:/PiScan
    command: 
      - /bin/bash
      - -c 
      - |
          tail -f /dev/null
